copy back from main

diff --git a/.github/workflows/benchmark-tmpl.yml b/.github/workflows/benchmark-tmpl.yml
--- a/.github/workflows/benchmark-tmpl.yml
+++ b/.github/workflows/benchmark-tmpl.yml
@@ -102,13 +102,20 @@ jobs:
           else
             bash ./runners/launch_${RUNNER_NAME%%_*}.sh
           fi
-          if [ "${RUN_BENCHMARK}" != "false" ]; then
+          FOUND_RESULT_FILE=
+          for i in {1..10}; do
             if [ -f "$RESULT_FILENAME.json" ]; then
               echo "RESULT_FILENAME=${RESULT_FILENAME}" >> $GITHUB_ENV
-            else
-              echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
-              exit 1
+              FOUND_RESULT_FILE=true
+              break
             fi
+            echo "Waiting for result file... (attempt $i)"
+            sleep 1
+          done
+   
+          if [ -z "$FOUND_RESULT_FILE" ]; then
+            echo "Run failed: Benchmark result $RESULT_FILENAME.json not found." >&2
+            exit 1
           fi
 
       - name: Process result
