di
Signed-off-by: seungrokj <seungrok.jung@amd.com>

diff --git a/.github/workflows/benchmark-tmpl.yml b/.github/workflows/benchmark-tmpl.yml
--- a/.github/workflows/benchmark-tmpl.yml
+++ b/.github/workflows/benchmark-tmpl.yml
@@ -113,24 +113,25 @@ jobs:
           #  done
           #fi
           #
-          ## Cleanup SLURM resources
-          #if command -v squeue >/dev/null 2>&1; then
-          #  if [[ "${{ runner.name }}" == mi355x-amds* ]]; then
-          #    echo "[Slurm] Cleaning up jobs with name: ${{ runner.name }} ..."
-          #    scancel --name="${{ runner.name }}" || true
-          #    while [ -n "$(squeue --name='${{ runner.name }}' --noheader --format='%i')" ]; do
-          #      squeue --name="${{ runner.name }}"
-          #      sleep 5
-          #    done
-          #  else
-          #    echo "[Slurm] Cleaning up jobs for user: $USER ..."
-          #    scancel -u "$USER" || true
-          #    while [ -n "$(squeue -u "$USER" --noheader --format='%i')" ]; do
-          #      squeue -u "$USER"
-          #      sleep 5
-          #    done
-          #  fi
-          #fi
+
+          # Cleanup SLURM resources
+          if command -v squeue >/dev/null 2>&1; then
+            if [[ "${{ runner.name }}" == mi355x-amds* ]]; then
+              echo "[Slurm] Cleaning up jobs with name: ${{ runner.name }} ..."
+              scancel --name="${{ runner.name }}" || true
+              while [ -n "$(squeue --name='${{ runner.name }}' --noheader --format='%i')" ]; do
+                squeue --name="${{ runner.name }}"
+                sleep 5
+              done
+            else
+              echo "[Slurm] Cleaning up jobs for user: $USER ..."
+              scancel -u "$USER" || true
+              while [ -n "$(squeue -u "$USER" --noheader --format='%i')" ]; do
+                squeue -u "$USER"
+                sleep 5
+              done
+            fi
+          fi
 
       - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
         with:
